version: 2.1
executors:
  python-executor:
    docker:
      - image: cimg/python:3.9.1

commands:
  install_requirements:
    description: "Installing requirements"
    steps:
      - run:
          name: Create virtualenv
          command: |
            cd project
            python -m venv /home/circleci/venv
            # Replace system python and pip to custom ones
            # echo export PATH=/home/circleci/venv/bin:$PATH'
      - run:
          name: Install actual requirements
          command: |
            sudo apt update
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Print lib versions
          command: pip freeze

  syntax_check:
    description: "Syntax checking"
    steps:
      - run:
          name: Lint with flake8
          command: |
            # GitHub editor is 127 chars wide
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  test_code:
    description: "Python code testing"
    steps:
      - run:
          name: Unit tests
          command: |
            # mock for tests
            export DB_DSN='postgresql+asyncpg://USERNAME:PASSWORD@$HOST/DB_NAME'
            export PYTHONPATH=$PYTHONPATH:/home/circleci/project
            if [ -d tests ]; then pytest tests --cov-config=tests/.coveragerc;fi

jobs:
  testing:
    executor: python-executor
    steps:
      - checkout
      - install_requirements
      - syntax_check
      - test_code

workflows:
  version: 2
  development_testing:
    jobs:
      - testing